apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: snapsentry-controller

patches:
  - target:
      kind: CronJob
      name: snapsentry-orchestrator
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/args
        value:
          - admin
          - orchestrator
          - --incluster
          - --log-level
          - info
          - --cloud
          - snapsentry-orchestartor

secretGenerator:
  - name: snapsentry-orchestartor-creds
    files:
      - clouds.yaml
