apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapsentry-orchestrator-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "pods"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapsentry-orchestrator-binding
subjects:
  - kind: ServiceAccount
    name: snapsentry-orchestrator-sa
roleRef:
  kind: Role
  name: snapsentry-orchestrator-role
  apiGroup: rbac.authorization.k8s.io
